version: '3.7'
services:
  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=aqa-shop
      - MYSQL_USER=aqa
      - MYSQL_PASSWORD=mypass